In [1]:
import pandas as pd

In [2]:
data = [
    {
        "Prompt": "Can you explain something without explaining it?",
        "Type": "Ambiguity",
        "Expected Issue": "Model may give vague or contradictory answer"
    },
    {
        "Prompt": "Give me a short answer in 1000 words.",
        "Type": "Contradiction",
        "Expected Issue": "Instruction conflict"
    },
    {
        "Prompt": "If all cats are animals and some animals are dogs, are all cats dogs?",
        "Type": "Logic Trap",
        "Expected Issue": "Incorrect logical reasoning"
    },
    {
        "Prompt": "He told him that he was wrong. Who is wrong?",
        "Type": "Context Confusion",
        "Expected Issue": "Ambiguous pronoun resolution"
    },
    {
        "Prompt": "Summarize this text: (very long irrelevant paragraph)",
        "Type": "Overload",
        "Expected Issue": "Loss of key information"
    }
]

df = pd.DataFrame(data)
df

,Prompt,Type,Expected Issue
0,Can you explain something without explaining it?,Ambiguity,Model may give vague or contradictory answer
1,Give me a short answer in 1000 words.,Contradiction,Instruction conflict
2,If all cats are animals and some animals are d...,Logic Trap,Incorrect logical reasoning
3,He told him that he was wrong. Who is wrong?,Context Confusion,Ambiguous pronoun resolution
4,Summarize this text: (very long irrelevant par...,Overload,Loss of key information

In [3]:
df["AI Response"] = [
    "Response 1 here",
    "Response 2 here",
    "Response 3 here",
    "Response 4 here",
    "Response 5 here"
]

In [4]:
df["Observation"] = [
    "Answer was vague and unclear",
    "Model ignored contradiction",
    "Incorrect logic used",
    "Could not resolve ambiguity",
    "Missed important points"
]

df

,Prompt,Type,Expected Issue,AI Response,Observation
0,Can you explain something without explaining it?,Ambiguity,Model may give vague or contradictory answer,Response 1 here,Answer was vague and unclear
1,Give me a short answer in 1000 words.,Contradiction,Instruction conflict,Response 2 here,Model ignored contradiction
2,If all cats are animals and some animals are d...,Logic Trap,Incorrect logical reasoning,Response 3 here,Incorrect logic used
3,He told him that he was wrong. Who is wrong?,Context Confusion,Ambiguous pronoun resolution,Response 4 here,Could not resolve ambiguity
4,Summarize this text: (very long irrelevant par...,Overload,Loss of key information,Response 5 here,Missed important points