In [1]:
import pandas as pd

In [2]:
resume_prompts = {
    "Weak": "Write a resume",
    
    "Strong": """Create a professional resume for a Computer Science student 
    skilled in Python, Machine Learning, and AWS. Include sections: Summary, 
    Skills, Projects, Education, and Certifications. Keep it concise and ATS-friendly."""
}

In [3]:
business_prompts = {
    "Weak": "Give me a business idea",
    
    "Strong": """Suggest a scalable tech-based business idea for India 
    targeting college students. Include problem, solution, revenue model, 
    and why it will succeed in the current market."""
}

In [4]:
study_prompts = {
    "Weak": "Make a study plan",
    
    "Strong": """Create a 30-day study plan for learning DevOps including 
    Linux, Docker, Kubernetes, and AWS basics. Allocate daily tasks 
    with practical exercises and revision strategy."""
}

In [5]:
data = [
    ["Resume", resume_prompts["Weak"], resume_prompts["Strong"]],
    ["Business Idea", business_prompts["Weak"], business_prompts["Strong"]],
    ["Study Plan", study_prompts["Weak"], study_prompts["Strong"]],
]

df = pd.DataFrame(data, columns=["Category", "Weak Prompt", "Strong Prompt"])
df

,Category,Weak Prompt,Strong Prompt
0,Resume,Write a resume,Create a professional resume for a Computer Sc...
1,Business Idea,Give me a business idea,Suggest a scalable tech-based business idea fo...
2,Study Plan,Make a study plan,Create a 30-day study plan for learning DevOps...

In [6]:
df["Weak Output"] = ["Output1", "Output2", "Output3"]
df["Strong Output"] = ["Output1", "Output2", "Output3"]

In [7]:
df["Observation"] = [
    "Weak prompt gives generic resume, strong prompt gives structured and relevant resume",
    "Weak prompt gives random idea, strong prompt gives detailed and practical idea",
    "Weak prompt gives vague plan, strong prompt gives step-by-step plan"
]

df

,Category,Weak Prompt,Strong Prompt,Weak Output,Strong Output,Observation
0,Resume,Write a resume,Create a professional resume for a Computer Sc...,Output1,Output1,"Weak prompt gives generic resume, strong promp..."
1,Business Idea,Give me a business idea,Suggest a scalable tech-based business idea fo...,Output2,Output2,"Weak prompt gives random idea, strong prompt g..."
2,Study Plan,Make a study plan,Create a 30-day study plan for learning DevOps...,Output3,Output3,"Weak prompt gives vague plan, strong prompt gi..."